#!/usr/bin/env bash

# Check the program does not have cerntain errors.
exit 0
if ! ~/circt/build/bin/circt-opt -export-verilog a.generic.mlir &> temp.txt ; then
  exit 1
fi


if grep -q "Wimplicit-int" temp.txt || \
   grep -q "defaulting to type" temp.txt || \
   grep -q "too few arguments" temp.txt ; then
  exit 1
fi

exit 0
# End of the check.
